    DROP FUNCTION IF EXISTS LIB_CRUD_CHECK;
    CREATE OR REPLACE FUNCTION LIB_CRUD_CHECK (
        VPFLAG VARCHAR
    ) RETURNS BOOLEAN
    AS $$
DECLARE

-- INFO. PORCEDURE
    INFSISTEMA   VARCHAR := 'LIB';
    INFPROCESO   VARCHAR := '00000';
    INFPROCEDURE VARCHAR := 'LIB_CRUD_CHECK';
    INFVERSION   VARCHAR := '2024.02.20.01';

-- VARIABLES
    VLERROR BOOLEAN := FALSE;

BEGIN

        INFPROCESO    := '00001';
        RETURN VPFLAG IN ('C','U','D');

END
$$ LANGUAGE PLPGSQL;