DROP FUNCTION IF EXISTS LIB_EMPTY;
CREATE OR REPLACE FUNCTION LIB_EMPTY (
    VPWORD VARCHAR
    ) RETURNS BOOLEAN
    AS $$
DECLARE

-- INFO. PORCEDURE
    INFSISTEMA   VARCHAR := 'LIB';
    INFPROCESO   VARCHAR := '00000';
    INFPROCEDURE VARCHAR := 'LIB_EMPTY';
    INFVERSION   VARCHAR := '2024.02.26';

BEGIN

    INFPROCESO    := '00001';
    IF LENGTH(VPWORD) > 0 THEN
        RETURN TRUE;
    END IF;

    RETURN FALSE;


END
$$ LANGUAGE PLPGSQL;